#%RAML 1.0
title: American FlightsDIY Api

types:
  AmericanFlights

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE

  post:
      

  /{ID}:
    get:
      

    