#%RAML 1.0
title: American FlightsDIY Api

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE

  post:
    queryParameters:
      destination:
        required: false
    headers:
      


  /{ID}:
    get:
      

    